"""added user stuff

Revision ID: 0c1b8c326a2c
Revises: 3b506dd2211e
Create Date: 2017-08-12 00:50:49.575000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1b8c326a2c'
down_revision = '3b506dd2211e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(op.f('uq_users_name'), 'users', ['name', 'email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_name'), 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', '_password')
    # ### end Alembic commands ###
