"""added_unique

Revision ID: 3b506dd2211e
Revises: 439cf451da16
Create Date: 2017-08-08 13:13:53.437000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b506dd2211e'
down_revision = '439cf451da16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_disc_golf_game_player_scores_hole_id'), 'disc_golf_game_player_scores', ['hole_id', 'player_id', 'score_card_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_disc_golf_game_player_scores_hole_id'), 'disc_golf_game_player_scores', type_='unique')
    # ### end Alembic commands ###
