"""empty message

Revision ID: 439cf451da16
Revises: 
Create Date: 2017-07-16 12:44:23.776000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439cf451da16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disc_golf_courses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disc_golf_frisbees',
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('disc_type', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disc_golf_players',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('my_dbs',
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disc_golf_games',
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('complete_date', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['disc_golf_courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disc_golf_holes',
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['disc_golf_courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players_frisbees',
    sa.Column('players_id', sa.Integer(), nullable=True),
    sa.Column('frisbees_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['frisbees_id'], ['disc_golf_frisbees.id'], ),
    sa.ForeignKeyConstraint(['players_id'], ['disc_golf_players.id'], )
    )
    op.create_table('disc_golf_score_cards',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['disc_golf_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players_games',
    sa.Column('players_id', sa.Integer(), nullable=True),
    sa.Column('games_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['games_id'], ['disc_golf_games.id'], ),
    sa.ForeignKeyConstraint(['players_id'], ['disc_golf_players.id'], )
    )
    op.create_table('disc_golf_game_player_scores',
    sa.Column('hole_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('score_card_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hole_id'], ['disc_golf_holes.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['disc_golf_players.id'], ),
    sa.ForeignKeyConstraint(['score_card_id'], ['disc_golf_score_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players_score_cards',
    sa.Column('players_id', sa.Integer(), nullable=True),
    sa.Column('score_cards_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['players_id'], ['disc_golf_players.id'], ),
    sa.ForeignKeyConstraint(['score_cards_id'], ['disc_golf_score_cards.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players_score_cards')
    op.drop_table('disc_golf_game_player_scores')
    op.drop_table('players_games')
    op.drop_table('disc_golf_score_cards')
    op.drop_table('players_frisbees')
    op.drop_table('disc_golf_holes')
    op.drop_table('disc_golf_games')
    op.drop_table('users')
    op.drop_table('my_dbs')
    op.drop_table('disc_golf_players')
    op.drop_table('disc_golf_frisbees')
    op.drop_table('disc_golf_courses')
    # ### end Alembic commands ###
