"""initial migration

Revision ID: 5e90e73ea910
Revises: ed3cccc5ccf4
Create Date: 2017-07-15 10:47:40.764000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e90e73ea910'
down_revision = 'ed3cccc5ccf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
