"""initial_migration

Revision ID: f7cccb49bf9b
Revises: 
Create Date: 2017-07-10 13:31:34.180078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cccb49bf9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disc_golf_score_cards', type_='foreignkey')
    op.drop_column('disc_golf_score_cards', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disc_golf_score_cards', sa.Column('course_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'disc_golf_score_cards', 'disc_golf_courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
